/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as PlansIndexRouteImport } from './routes/plans/index'
import { Route as PlansPlanIdRouteImport } from './routes/plans/$planId'
import { Route as SettingsHouseholdRouteImport } from './routes/settings/household'
import { Route as SettingsModulesRouteImport } from './routes/settings/modules'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as StagePlaybillRouteImport } from './routes/stage/playbill'
import { Route as StageVisitsRouteImport } from './routes/stage/visits'
import { Route as StageWatchlistRouteImport } from './routes/stage/watchlist'
import { Route as TravelSavedRouteImport } from './routes/travel/saved'
import { Route as StageProductionsProductionIdRouteImport } from './routes/stage/productions/$productionId'
import { Route as StageWorksIndexRouteImport } from './routes/stage/works/index'
import { Route as StageWorksWorkIdRouteImport } from './routes/stage/works/$workId'
import { Route as TravelOffersIndexRouteImport } from './routes/travel/offers/index'
import { Route as TravelOffersOfferIdRouteImport } from './routes/travel/offers/$offerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdRoute = PlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHouseholdRoute = SettingsHouseholdRouteImport.update({
  id: '/settings/household',
  path: '/settings/household',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsModulesRoute = SettingsModulesRouteImport.update({
  id: '/settings/modules',
  path: '/settings/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StagePlaybillRoute = StagePlaybillRouteImport.update({
  id: '/stage/playbill',
  path: '/stage/playbill',
  getParentRoute: () => rootRouteImport,
} as any)
const StageVisitsRoute = StageVisitsRouteImport.update({
  id: '/stage/visits',
  path: '/stage/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const StageWatchlistRoute = StageWatchlistRouteImport.update({
  id: '/stage/watchlist',
  path: '/stage/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelSavedRoute = TravelSavedRouteImport.update({
  id: '/travel/saved',
  path: '/travel/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const StageProductionsProductionIdRoute =
  StageProductionsProductionIdRouteImport.update({
    id: '/stage/productions/$productionId',
    path: '/stage/productions/$productionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StageWorksIndexRoute = StageWorksIndexRouteImport.update({
  id: '/stage/works/',
  path: '/stage/works/',
  getParentRoute: () => rootRouteImport,
} as any)
const StageWorksWorkIdRoute = StageWorksWorkIdRouteImport.update({
  id: '/stage/works/$workId',
  path: '/stage/works/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelOffersIndexRoute = TravelOffersIndexRouteImport.update({
  id: '/travel/offers/',
  path: '/travel/offers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelOffersOfferIdRoute = TravelOffersOfferIdRouteImport.update({
  id: '/travel/offers/$offerId',
  path: '/travel/offers/$offerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/inbox': typeof InboxRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/settings/household': typeof SettingsHouseholdRoute
  '/settings/modules': typeof SettingsModulesRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/stage/playbill': typeof StagePlaybillRoute
  '/stage/visits': typeof StageVisitsRoute
  '/stage/watchlist': typeof StageWatchlistRoute
  '/travel/saved': typeof TravelSavedRoute
  '/plans/': typeof PlansIndexRoute
  '/stage/productions/$productionId': typeof StageProductionsProductionIdRoute
  '/stage/works/$workId': typeof StageWorksWorkIdRoute
  '/travel/offers/$offerId': typeof TravelOffersOfferIdRoute
  '/stage/works/': typeof StageWorksIndexRoute
  '/travel/offers/': typeof TravelOffersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/inbox': typeof InboxRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/settings/household': typeof SettingsHouseholdRoute
  '/settings/modules': typeof SettingsModulesRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/stage/playbill': typeof StagePlaybillRoute
  '/stage/visits': typeof StageVisitsRoute
  '/stage/watchlist': typeof StageWatchlistRoute
  '/travel/saved': typeof TravelSavedRoute
  '/plans': typeof PlansIndexRoute
  '/stage/productions/$productionId': typeof StageProductionsProductionIdRoute
  '/stage/works/$workId': typeof StageWorksWorkIdRoute
  '/travel/offers/$offerId': typeof TravelOffersOfferIdRoute
  '/stage/works': typeof StageWorksIndexRoute
  '/travel/offers': typeof TravelOffersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/inbox': typeof InboxRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/settings/household': typeof SettingsHouseholdRoute
  '/settings/modules': typeof SettingsModulesRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/stage/playbill': typeof StagePlaybillRoute
  '/stage/visits': typeof StageVisitsRoute
  '/stage/watchlist': typeof StageWatchlistRoute
  '/travel/saved': typeof TravelSavedRoute
  '/plans/': typeof PlansIndexRoute
  '/stage/productions/$productionId': typeof StageProductionsProductionIdRoute
  '/stage/works/$workId': typeof StageWorksWorkIdRoute
  '/travel/offers/$offerId': typeof TravelOffersOfferIdRoute
  '/stage/works/': typeof StageWorksIndexRoute
  '/travel/offers/': typeof TravelOffersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/inbox'
    | '/plans/$planId'
    | '/settings/household'
    | '/settings/modules'
    | '/settings/notifications'
    | '/settings/profile'
    | '/stage/playbill'
    | '/stage/visits'
    | '/stage/watchlist'
    | '/travel/saved'
    | '/plans/'
    | '/stage/productions/$productionId'
    | '/stage/works/$workId'
    | '/travel/offers/$offerId'
    | '/stage/works/'
    | '/travel/offers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/inbox'
    | '/plans/$planId'
    | '/settings/household'
    | '/settings/modules'
    | '/settings/notifications'
    | '/settings/profile'
    | '/stage/playbill'
    | '/stage/visits'
    | '/stage/watchlist'
    | '/travel/saved'
    | '/plans'
    | '/stage/productions/$productionId'
    | '/stage/works/$workId'
    | '/travel/offers/$offerId'
    | '/stage/works'
    | '/travel/offers'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/inbox'
    | '/plans/$planId'
    | '/settings/household'
    | '/settings/modules'
    | '/settings/notifications'
    | '/settings/profile'
    | '/stage/playbill'
    | '/stage/visits'
    | '/stage/watchlist'
    | '/travel/saved'
    | '/plans/'
    | '/stage/productions/$productionId'
    | '/stage/works/$workId'
    | '/travel/offers/$offerId'
    | '/stage/works/'
    | '/travel/offers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  InboxRoute: typeof InboxRoute
  PlansPlanIdRoute: typeof PlansPlanIdRoute
  SettingsHouseholdRoute: typeof SettingsHouseholdRoute
  SettingsModulesRoute: typeof SettingsModulesRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  StagePlaybillRoute: typeof StagePlaybillRoute
  StageVisitsRoute: typeof StageVisitsRoute
  StageWatchlistRoute: typeof StageWatchlistRoute
  TravelSavedRoute: typeof TravelSavedRoute
  PlansIndexRoute: typeof PlansIndexRoute
  StageProductionsProductionIdRoute: typeof StageProductionsProductionIdRoute
  StageWorksWorkIdRoute: typeof StageWorksWorkIdRoute
  TravelOffersOfferIdRoute: typeof TravelOffersOfferIdRoute
  StageWorksIndexRoute: typeof StageWorksIndexRoute
  TravelOffersIndexRoute: typeof TravelOffersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId': {
      id: '/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/household': {
      id: '/settings/household'
      path: '/settings/household'
      fullPath: '/settings/household'
      preLoaderRoute: typeof SettingsHouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/modules': {
      id: '/settings/modules'
      path: '/settings/modules'
      fullPath: '/settings/modules'
      preLoaderRoute: typeof SettingsModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage/playbill': {
      id: '/stage/playbill'
      path: '/stage/playbill'
      fullPath: '/stage/playbill'
      preLoaderRoute: typeof StagePlaybillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage/visits': {
      id: '/stage/visits'
      path: '/stage/visits'
      fullPath: '/stage/visits'
      preLoaderRoute: typeof StageVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage/watchlist': {
      id: '/stage/watchlist'
      path: '/stage/watchlist'
      fullPath: '/stage/watchlist'
      preLoaderRoute: typeof StageWatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel/saved': {
      id: '/travel/saved'
      path: '/travel/saved'
      fullPath: '/travel/saved'
      preLoaderRoute: typeof TravelSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage/productions/$productionId': {
      id: '/stage/productions/$productionId'
      path: '/stage/productions/$productionId'
      fullPath: '/stage/productions/$productionId'
      preLoaderRoute: typeof StageProductionsProductionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage/works/': {
      id: '/stage/works/'
      path: '/stage/works'
      fullPath: '/stage/works/'
      preLoaderRoute: typeof StageWorksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage/works/$workId': {
      id: '/stage/works/$workId'
      path: '/stage/works/$workId'
      fullPath: '/stage/works/$workId'
      preLoaderRoute: typeof StageWorksWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel/offers/': {
      id: '/travel/offers/'
      path: '/travel/offers'
      fullPath: '/travel/offers/'
      preLoaderRoute: typeof TravelOffersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel/offers/$offerId': {
      id: '/travel/offers/$offerId'
      path: '/travel/offers/$offerId'
      fullPath: '/travel/offers/$offerId'
      preLoaderRoute: typeof TravelOffersOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  InboxRoute: InboxRoute,
  PlansPlanIdRoute: PlansPlanIdRoute,
  SettingsHouseholdRoute: SettingsHouseholdRoute,
  SettingsModulesRoute: SettingsModulesRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  StagePlaybillRoute: StagePlaybillRoute,
  StageVisitsRoute: StageVisitsRoute,
  StageWatchlistRoute: StageWatchlistRoute,
  TravelSavedRoute: TravelSavedRoute,
  PlansIndexRoute: PlansIndexRoute,
  StageProductionsProductionIdRoute: StageProductionsProductionIdRoute,
  StageWorksWorkIdRoute: StageWorksWorkIdRoute,
  TravelOffersOfferIdRoute: TravelOffersOfferIdRoute,
  StageWorksIndexRoute: StageWorksIndexRoute,
  TravelOffersIndexRoute: TravelOffersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
