// <auto-generated />
using System;
using Allet.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Allet.Web.Migrations
{
    [DbContext(typeof(AlletDbContext))]
    [Migration("20260215030634_AddProductions")]
    partial class AddProductions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Allet.Web.Models.Production", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("season");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_productions");

                    b.HasIndex("Source", "Slug", "Season")
                        .IsUnique()
                        .HasDatabaseName("ix_productions_source_slug_season");

                    b.ToTable("productions", (string)null);
                });

            modelBuilder.Entity("Allet.Web.Models.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int?>("ProductionId")
                        .HasColumnType("integer")
                        .HasColumnName("production_id");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<int?>("VenueId")
                        .HasColumnType("integer")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_shows");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_shows_venue_id");

                    b.HasIndex("ProductionId", "VenueId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_shows_production_id_venue_id_date")
                        .HasFilter("production_id IS NOT NULL AND venue_id IS NOT NULL AND date IS NOT NULL");

                    b.ToTable("shows", (string)null);
                });

            modelBuilder.Entity("Allet.Web.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("ShowId")
                        .HasColumnType("integer")
                        .HasColumnName("show_id");

                    b.Property<string>("TargetValue")
                        .HasColumnType("text")
                        .HasColumnName("target_value");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("ShowId")
                        .HasDatabaseName("ix_subscriptions_show_id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("Allet.Web.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_venues");

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("Allet.Web.Models.Show", b =>
                {
                    b.HasOne("Allet.Web.Models.Production", "Production")
                        .WithMany("Shows")
                        .HasForeignKey("ProductionId")
                        .HasConstraintName("fk_shows_productions_production_id");

                    b.HasOne("Allet.Web.Models.Venue", "Venue")
                        .WithMany("Shows")
                        .HasForeignKey("VenueId")
                        .HasConstraintName("fk_shows_venues_venue_id");

                    b.Navigation("Production");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Allet.Web.Models.Subscription", b =>
                {
                    b.HasOne("Allet.Web.Models.Show", "Show")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_shows_show_id");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Allet.Web.Models.Production", b =>
                {
                    b.Navigation("Shows");
                });

            modelBuilder.Entity("Allet.Web.Models.Show", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Allet.Web.Models.Venue", b =>
                {
                    b.Navigation("Shows");
                });
#pragma warning restore 612, 618
        }
    }
}
